services:
  prometheus:
    image: "prom/prometheus"
    volumes:
      - ./prometheus:/etc/prometheus
    network_mode: host

  grafana:
    image: grafana/grafana
    network_mode: host
    volumes:
      - ./grafana/conf/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/conf/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards