services:
  prometheus:
    image: "prom/prometheus"
    volumes:
      - ./prometheus:/etc/prometheus
    network_mode: host

  grafana:
    image: grafana/grafana
    network_mode: host
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage: