{
 "title": "Speedtest",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(speedtest_latency_speed_bucket[$__rate_interval])) by (le,isp))",
     "legendFormat": "{{isp}}"
    }
   ]
  },
  {
   "title": "Current",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(speedtest_latency_speed_bucket[$__rate_interval])) by (le))",
     "legendFormat": "{{isp}}"
    }
   ]
  },
  {
   "title": "Download",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(speedtest_download_speed_bucket[$__rate_interval])) by (le,isp))",
     "legendFormat": "{{isp}}"
    }
   ]
  },
  {
   "title": "Current",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(speedtest_download_speed_bucket[$__rate_interval])) by (le))",
     "legendFormat": "{{isp}}"
    }
   ]
  },
  {
   "title": "Upload",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(speedtest_upload_speed_bucket[$__rate_interval])) by (le,isp))",
     "legendFormat": "{{isp}}"
    }
   ]
  },
  {
   "title": "Current",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(speedtest_upload_speed_bucket[$__rate_interval])) by (le))",
     "legendFormat": "{{isp}}"
    }
   ]
  }
 ]
}